# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'QQNewFeaturesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 3.2.1'
  pod 'UIView+Frame', '~> 1.0.2'
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'LKDBHelper', '~> 2.5.1'
  pod 'MJExtension', '~> 3.1.0'


  target 'QQNewFeaturesDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QQNewFeaturesDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
